name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  TF_VERSION        : "1.2.8"
  AWS_REGION        : "eu-west-2"
  AWS_ROLE_TO_ASSUME : "arn:aws:iam::948691256895:role/gh-action"
  ECR_REGISTRY_URL : "948691256895.dkr.ecr.eu-west-2.amazonaws.com/su-bill-report"
  LAMBDA_FUNC_NAME   : "su-bill-report-lambda"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Configure aws CLI profile
      #   uses: ./.github/actions/aws-configure
      #   with:
      #     aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key_id: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws_default_region: ${{ env.AWS_DEFAULT_REGION }}
      #     aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
      #     aws_profile_name: "default"

      - name: Building and pushing image to registry
        uses: ./.github/actions/build-and-push
        with:
          ecr_registry_url: ${{ env.ECR_REGISTRY_URL }}
          image_tag: "v${{ github.run_number }}"

      - name: Update lambda image version
        run: |
          aws lambda update-function-code \
            --function-name  ${{ env.LAMBDA_FUNC_NAME }} \
            --image-uri ${{ env.ECR_REGISTRY_URL }}:"v${{ github.run_number }}"


      


  